#!/usr/bin/env node
/**
 * Generate version.ts file from package.json
 * This ensures VERSION is available in all build outputs (UMD, ESM, CJS)
 */

const fs = require('fs');
const path = require('path');

try {
  // Read package.json
  const packageJsonPath = path.join(__dirname, '../package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

  if (!packageJson.version) {
    console.error('Error: No version found in package.json');
    process.exit(1);
  }

  // Generate version.ts content with proper documentation
  const versionFilePath = path.join(__dirname, '../src/version.ts');
  const versionFileContent = `/**
 * SDK version - auto-generated from package.json
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is automatically generated during the build process.
 * To update the version, modify package.json
 */

export const VERSION = '${packageJson.version}';
`;

  // Write the file
  fs.writeFileSync(versionFilePath, versionFileContent, 'utf8');
  console.log(`✓ Generated version.ts with version ${packageJson.version}`);
} catch (error) {
  console.error('Error generating version.ts:', error.message);
  process.exit(1);
}
